const menu = [
  {
    id: 2,
    title: "Eggs Benedict",
    category: "Breakfast",
    price: 12.99,
    img: "./images/item-2.jpeg",
    desc: "Organic eggs, Canadian bacon, and hollandaise sauce on an English muffin",
  },
  {
    id: 3,
    title: "Avocado Toast",
    category: "Evening",
    price: 9.99,
    img: "./images/item-3.jpeg",
    desc: "Toasted artisan bread topped with mashed avocado, sea salt, and fresh herbs",
  },
  {
    id: 4,
    title: "Belgian Waffles",
    category: "Breakfast",
    price: 14.99,
    img: "./images/item-4.jpeg",
    desc: "Golden brown Belgian waffles served with whipped cream and maple syrup",
  },
  {
    id: 5,
    title: "French Toast",
    category: "Morning",
    price: 11.99,
    img: "./images/item-5.jpeg",
    desc: "Thick slices of bread soaked in a mixture of eggs, milk, and cinnamon, then fried to perfection",
  },
  {
    id: 6,
    title: "Omelette",
    category: "Breakfast",
    price: 13.99,
    img: "./images/item-6.jpeg",
    desc: "Fluffy omelette filled with your choice of ingredients such as cheese, vegetables, and ham",
  },
  {
    id: 7,
    title: "Breakfast Burrito",
    category: "Dinner",
    price: 10.99,
    img: "./images/item-7.jpeg",
    desc: "A hearty burrito filled with scrambled eggs, bacon, cheese, and salsa",
  },
  {
    id: 8,
    title: "Fruit Parfait",
    category: "Breakfast",
    price: 8.99,
    img: "./images/item-8.jpeg",
    desc: "Layers of fresh fruits, yogurt, and granola, served in a glass",
  },
  {
    id: 9,
    title: "Breakfast Croissant",
    category: "Breakfast",
    price: 7.99,
    img: "./images/item-9.jpeg",
    desc: "Flaky croissant filled with scrambled eggs, cheese, and your choice of ham or bacon",
  },
  {
    id: 10,
    title: "Pancakes with",
    category: "Starter",
    price: 16.99,
    img: "./images/item-10.jpeg",
    desc: "Delicious pancakes topped with a variety of fresh berries and whipped cream",
  },
  {
    id: 11,
    title: "Pancakes with",
    category: "Breakfast",
    price: 16.99,
    img: "./images/item-10.jpeg",
    desc: "Delicious pancakes topped with a variety of fresh berries and whipped cream",
  },
  {
    id: 12,
    title: "Pancakes with",
    category: "Shake",
    price: 16.99,
    img: "./images/item-10.jpeg",
    desc: "Delicious pancakes topped with a variety of fresh berries and whipped cream",
  },
];
export default menu;
